# This is another way of defining hte properties in the yml file.
# see this link: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

server:
  error:
    whitelabel:
      enabled: false
  port: ${port:8083}

spring:
  application:
    name: irfanstore-apigateway
  profiles:
      active: development

security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false

